spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
            redirect-uri: ""
            scope:
              - openid
              - profile
              - email

          kakao:
            client-id:
            client-secret:
            redirect-uri: ""
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-name: Kakao

          naver:
            client-id:
            client-secret:
            redirect-uri: ""
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.security.test1: DEBUG

jwt:
  secret:
  expiration: 86400000

app:
  frontend:
    url: http://localhost:5173


toss:
    cert:
      client-id:
      client-secret: